version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: codedeploy/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: codedeploy/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: codedeploy/stop_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: codedeploy/validate_service.sh
      timeout: 300
      runas: root