version: "3.7"
services: 
  client: 
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    #image: pawelfraczyk/bgshop
    restart: always
    ports:
      - "3000:3000"
    networks:
      bgshop_net:

  api:
    container_name: api
    image: pawelfraczyk/bgshop-api
    restart: always
    env_file: .env
    environment:
      - MONGO_USER=$MONGO_USER
      - MONGO_PASS=$MONGO_PASS
      - MONGO_HOST=mongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "2370:2370"
    networks:
      bgshop_net:
    depends_on:
      - mongo
  
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASS
    ports:
      - "27017:27017"
    networks:
      bgshop_net:

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - api
    networks:
      bgshop_net:
        
  mongo_seed:
    container_name: mongo_seed
    build: mongo-seed/.
    networks:
      bgshop_net:
    depends_on:
      - mongo

networks:
  bgshop_net: