# from base_prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'aws_nodes'
    metrics_path: '/metrics'
    ec2_sd_configs:
      - region: 'eu-west-1'
        port: 9100
  - job_name: 'aws_containers'
    ec2_sd_configs:
      - region: 'eu-west-1'
        port: 8080