version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.16
  aws-code-deploy: circleci/aws-code-deploy@0.0.9

jobs:
  deploy_to_staging:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/setup
      - aws-code-deploy/push-bundle:
          application-name: bgshop-app
          bundle-bucket: bgshop-codedeploy-bucket
          bundle-key: codedeploy/$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM
      - aws-code-deploy/deploy-bundle:
          application-name: bgshop-app
          deployment-group: calluna-ci-pf-sandbox-staging-main_app-group
          bundle-bucket: bgshop-codedeploy-bucket
          bundle-key: codedeploy/$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM

workflows:
  deploy:
    jobs:
      - deploy_to_staging:
          filters:
            branches:
              only: master