version: "3.7"

networks:
  tools: {}

volumes:
  grafana_lib: {}
  prometheus_data: {}
  prometheus_config:
    driver_opts:
      type: tmpfs
      device: tmpfs

services:
  prometheus:
    image: prom/prometheus:v2.19.0
    ports:
      - 9090:9090
    networks:
      tools:
    volumes:
      - prometheus_data:/prometheus
      - prometheus_config:/fragments/
    command:
      - '--config.file=/fragments/complete/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:7.0.3
    ports:
      - "3000:3000"
    networks:
      tools:
    volumes:
      - grafana_lib:/var/lib/grafana
      - ${PWD}/config/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    environment:
      # TODO with SSM parameter store
      - GF_SECURITY_ADMIN_PASSWORD=$GF_SECURITY_ADMIN_PASSWORD

  config-concat:
    image: deanwilson/promconf-concat:0.1.0
    volumes:
      - prometheus_config:/fragments/
      - ${PWD}/config/base_prometheus.yml:/base_prometheus.yml
  
  node-exporter:
    image: prom/node-exporter:v0.18.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      tools:

  mongo:
    image: mongo:4.2
    networks:
      tools:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      tools:

  graylog:
    image: graylog/graylog:4.0
    environment:
      #- GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      #- GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=$GRAYLOG_HTTP_EXTERNAL_URI
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    volumes:
      - ${PWD}/config/graylog:/usr/share/graylog/data/contentpacks
    networks:
      tools:
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # GELF UDP
      - 12201:12201/udp

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks:
      tools:

  wait-for:
    image: busybox:latest
    entrypoint: ["sh", "-c"]
    networks:
      tools:
    command:
      - |
          END_TIME=$$(( $$(date +%s) + 60 ));
          while [ $$(date +%s) -lt $$END_TIME ]; do
              if nc -w 3 -z -v ${HOST:-graylog} ${PORT:-9000}; then
                exit 0;
              fi
              echo "Waiting for ${HOST:-graylog} to be up and running.."
              sleep 1
          done
          echo "Could not establish tcp connection to ${HOST:-graylog}:${PORT:-9000}"
          exit 1;